mratsim/weave

- e04_channel_based_work_stealing/affinity.nim
- e04_channel_based_work_stealing/primitives/pthread_barrier_osx.nim
- e04_channel_based_work_stealing/primitives/threads.nim
- e04_channel_based_work_stealing/runtime.nim
- e04_channel_based_work_stealing/tasking_runtime.nim
1. Implement pthread_barrier
2. Understand why pthread_create doesn't properly restore the pointer passed as the 4th argument on OSX (casting to int shows no change but using repr shows truncation)
> OSX compat

- weave/datatypes/context_thread_local.nim
- weave/datatypes/sync_types.nim
- weave/memory/persistacks.nim
- weave/scheduler.nim
- weave/thieves.nim
- weave/workers.nim
20% speed increase on LazyFlowvar and 5% speed increase on eager flowvar
Seems like it's a keep. (closes #7)
Lazy with ptr Steal request on fib(40) with 36 threads
```
real    0m0.179s
user    0m6.018s
sys     0m0.020s
```
Lazy without
```
real    0m0.230s
user    0m7.846s
sys     0m0.010s
```
-----------------------------------------------------------------------
Eager with
```
real    0m0.434s
user    0m15.143s
sys     0m0.017s
```
Eager without
```
real    0m0.483s
user    0m16.789s
sys     0m0.020s
```
-----------------------------------------------------------------
The original port as the same perf as the C code and serves as a reference perf.
The LazyFutures was a bit slower and the Eager future was a bit faster
Lazy
```
real    0m0.299s
user    0m10.253s
sys     0m0.014s
``` …
> Use steal requests as pointers

- weave/datatypes/context_thread_local.nim
- weave/datatypes/sparsesets.nim
- weave/memory/object_pools.nim
- weave/random/rng.nim
- weave/scheduler.nim
- weave/targets.nim
This changes the RNG from the C stdlib which only has 32-bit of state to xoshiro256++ which is a robust general purpose RNG.
Compared to Nim default:
- It avoids the awkward -1, +1 for the inclusive ranges.
- The lower bits of xoroshiro128+ (and any + algo of that family) have low linearity, meaning taking a modulo with a low number is somewhat bad (but this is also true for Mersenne Twister and may others).
The workaround is to use a ++ or a ** algorithm or only use the higher bits via shifting.
- It should be slightly slower but due to the large instruction level parallelism on xor it should take still below a nanosecond to generate a random number.
Measured no perf difference
> Use more robust RNG

- weave/async.nim
- weave/channels/channels_mpsc_unbounded.nim
- weave/contexts.nim
- weave/datatypes/context_global.nim
- weave/datatypes/sparsesets.nim
- weave/datatypes/sync_types.nim
- weave/primitives/compiler_optimization_hints.nim
- weave/runtime.nim
- weave/scheduler.nim
- weave/thieves.nim
- weave/victims.nim
Implemented lockless unbounded MPSC channels.
The initial implementation was based on snmalloc paper (itself inspired by Pony).
The idea was to use it for both:
- the future memory pool that needs a way to transfer onership of memory block back to the thread that allocated them in the first place
- steal request
However they have the following issues:
- they hold on the last item of a queue (breaking for steal requests)
- they require memory management of the dummy node (snmalloc deletes it and its memory doesn't seem to be reclaimed)
- they never touch the "back" pointer of the queue when dequeuing, meaning if an item was last, dequeuing will still points to it. Pony has an emptiness check via tagged pointer and snmalloc does something unknown.
On fib(40) with i9-9980XE (36 cores OC @ …
> Change to lockless unbounded mpsc

- weave/channels/event_notifiers.nim
- weave/config.nim
- weave/contexts.nim
- weave/datatypes/binary_worker_trees.nim
- weave/datatypes/context_global.nim
- weave/runtime.nim
- weave/scheduler.nim
- weave/signals.nim
- weave/thieves.nim
- weave/victims.nim
see #27.
First tentative was to create a transaction system with a commit/rollback mechanism
but it doesn't seem to work.
Plus the PR is really ugly due to enum not being atomics https://github.com/nim-lang/Nim/issues/12812
For now backoff will be deactivated and revisited later.
> Undeadlock the backoff

- weave/channels/channels_spsc_single_ptr.nim
- weave/memory/lookaside_lists.nim
We had to remove the attempt to avoid monomorphization code bloat in the ptr channels. As they were inline for every procedure and only used for the Task type anyway it probably doesn't change anything regarding code size.
> C++ compatibility

- .travis.yml
- LICENSE-APACHEv2
- LICENSE-MIT
- README.md
- benchmarks/matrix_transposition/weave_transposes.nim
- benchmarks/nqueens/weave_nqueens.nim
- weave.nimble
- weave/config.nim
- weave/datatypes/sparsesets.nim
- weave/parallel_for.nim
- weave/parallel_for_staged.nim
- Nimble configuration
- fine-grained tests of everything testable
- Disable Backoff by default due to #43
- Better report of the nqueens benchmark
- Travis CI
> Package weave for release

- changelog.md
- weave/channels/event_notifiers.nim
- weave/config.nim
- weave/datatypes/context_global.nim
- weave/primitives/futex_linux.nim
This replaces Lock+Condition variables by futex on Linux.
It solves the nasty #56 bug which is due to a Glibc and Musl bug on condvar signaling not waking up all thread.
Would be nice to use futex on Windows as well as they are supported there and are much more lightweight than condition variables + lock (4 bytes vs ~72 bytes on Linux) plus we don't need all the extra fluff that mutexes and condition variables have to guard against as we have formally verified that just wait+wake is enough.
> Me 1 - 0 Glibc: replace buggy Glibc condvar by futex

- weave/channels/channels_spsc_single.nim
- weave/contexts.nim
- weave/datatypes/flowvars.nim
- weave/datatypes/prell_deques.nim
- weave/memory/lookaside_lists.nim
- weave/memory/memory_pools.nim
- weave/memory/thread_id.nim
- weave/runtime.nim
- weave/scheduler.nim
This fixes #42.
The memory pool requires an unique ThreadID to identify if the memory being recycled can use the fast-path because it is thread-local or use a slow thread-safe recycling path.
However usual ways of getting a unique threadID via pthread_self or GetThreadID requires a syscall, which are **very** expensive (100 of cycles at the very least) and a complete non-starter.
Previously this required all data structures that to remember a threadID, and pass it when recycling memory, now the memory pool ha sthe same API as regular malloc/free.
This instead uses the address of the thread-local storage as an unique ID and only requires 1 cycle provided the function is inlined.
> No syscall portable threadid

- .gitmodules
- benchmarks/matmul_gemm_blas/mkldnn_gemm_jit_avx2.nim
- benchmarks/matmul_gemm_blas/mkldnn_gemm_jit_avx512.nim
- benchmarks/vendor/mkldnn.nim
- benchmarks/vendor/mkldnn_config.h
- benchmarks/vendor/mkldnn_version.h
Add a benchmark vs the reference deep-learning CPU acceleration library.
MKL-DNN achieves 2TFlops with AVX2 on my machine (4GHz all-core Turbo) and 3TFlops with AVX512 (3.5GHz all-core turbo) however AVX512 is unstable and probably requires further downclocking. This does not happen with raw MKL (which achieves 3.1TFlops)
> Matrix Mult bench vs Intel MKL-DNN

- benchmarks/matrix_transposition/openmp_transposes.nim
- weave/loop_splitting.nim
- weave/parallel_for.nim
We were sending `roundPrevMultipleOf(task.stop - chunk*task.stride, chunk*task.stride)` instead of `roundPrevMultipleOf(task.stop - chunk*task.stride, task.stride)` for strided loop which often meant sending everything and having no tasks left.
> Strided loop splitting bug

- .travis.yml
- experiments/e04_channel_based_work_stealing/runtime.nim
- weave.nimble
- weave/await_fsm.nim
- weave/contexts.nim
- weave/datatypes/prell_deques.nim
- weave/datatypes/sync_types.nim
- weave/parallel_for.nim
- weave/runtime.nim
- weave/runtime_fsm.nim
- weave/scheduler.nim
- weave/signals.nim
- weave/victims.nim
The batch field is not necessary. Upon received bundled tasks, the thief had to iterate on them to find the tail anyway
> Reduce metadata in task descriptor

- benchmarks/xxx_pathological/histogram_2D/weave_histogram.nim
- benchmarks/xxx_pathological/logsumexp/weave_logsumexp.nim
- weave/await_fsm.nim
- weave/config.nim
- weave/datatypes/context_thread_local.nim
- weave/datatypes/sync_types.nim
- weave/runtime_fsm.nim
- weave/scheduler.nim
- weave/signals.nim
- weave/targets.nim
- weave/thieves.nim
- weave/victims.nim
This adds the LastThief and LastVictim steal policies.
LastVictim in particular is optimal for long-running tasks over 35 microseconds.
https://epub.uni-bayreuth.de/2990
Compared to the orginal code, Weave fine-grained parallelism has been tremendously improved thanks to the custom memory pool (#24). Furthermore, unlike in the thesis, Weave MPSC channels are lockless and very fast for producers as they only require an exchange (and not a compare exchange). In the thesis it is mentioned that both are equivalent in terms of total messages sent probability if sending task (SPSC channel) and sending steal request (MPSC channel) have the same cost with last victim achieving greater efficiency (much more likely to steal successfully on the first try).
Due to the:
- lockless MPSC channels in …
> Victim selection

- weave/config.nim
- weave/loop_splitting.nim
- weave/memory/memory_pools.nim
- weave/parallel_for.nim
- weave/parallel_for_staged.nim
- weave/parallel_reduce.nim
- weave/scheduler.nim
- weave/scheduler_fsm.nim
- weave/victims.nim
- weave/workers.nim
Fixes #76 addresses https://github.com/mratsim/weave/issues/68#issuecomment-569421724
Now GEMM is nearly at 2.4 TFlops. 300MFlops left to reach OpenMP performance on coarse grained matrix multiplication loop.
```
Backend:                        Weave (Pure Nim)
Type:                           float32
A matrix shape:                 (M: 1920, N: 1920)
B matrix shape:                 (M: 1920, N: 1920)
Output shape:                   (M: 1920, N: 1920)
Required number of operations: 14155.776 millions
Required bytes:                   29.491 MB
Arithmetic intensity:            480.000 FLOP/byte
Theoretical peak single-core:    224.000 GFLOP/s
Theoretical peak multi:         4032.000 GFLOP/s
Weave implementation
Collected 300 samples in 2044 ms
Average time: 5.907 ms
Stddev  time: 0.967 ms …
```
> Fix splitted tasks wakeup

- weave/contexts.nim
- weave/datatypes/context_thread_local.nim
- weave/victims.nim
- weave/workers.nim
Experiments for one last push in matrix multiplication throughput.
A couple of areas were explored:
1. (inconclusive) in `schedule(Task)` if the current task is splittable that means that it just created a task and so it's a loop that generates task and it should be valuable to split it.
Unfortunately when encountering a for loop that generates task, Weave will quickly create many tasks so what will probably happen is that a loop that generate tasks is likely light in actual compute so sending the generated tasks directly is the same as sending a loop iteration.
2. (drop perf) Inverting the order of splitting the current task and sending a task from the deque. The issue with that strategy is that unless in `schedule(Task)` in other proc like shareWork/handleThieves (which call …
> Nested data parallelism experiments

- weave/channels/channels_mpsc_unbounded_batch.nim
- weave/channels/pledges.nim
- weave/config.nim
- weave/memory/memory_pools.nim
This addresses part of #93, reducing the MPSC padding so that the data structure fits in 192 bytes leaving enough space for it to be used intrusively in memory pool allocated data structure like pledges.
Unfortunately the {.align.} pragma for generics is actually not applied so MPSC Channel is not padded.
This means that currently cache conflicts between threads are high and performance will be increased (especially on the steal requests overhead front), but it may also cause size issues in the future.
See upstream: https://github.com/nim-lang/Nim/issues/13122
> Reduce mpsc padding

- weave/parallel_macros.nim
- weave/parallel_reduce.nim
- weave/parallel_tasks.nim
After your change for `isRootTask`, `readyWith` also complained.
I also changed it in `parallel_reduce` and `parallel_macros`, since I assume the problem will happen with those under the same circumstances as well.
> also avoid UFCS for `readyWith`

- weave/channels/channels_mpsc_unbounded_batch.nim
- weave/channels/pledges.nim
- weave/memory/memory_pools.nim
This updates the MPSC channel padding after the fix of https://github.com/nim-lang/Nim/issues/13122
There is a tricky compromise for the pledges data structure size:
https://github.com/mratsim/weave/blob/71cf68137bd27e9ba175b468a342a8e61a647faa/weave/channels/pledges.nim#L146-L173
The `kind` field (1 byte) has to be the first field of PledgePtr, so when the `ChannelMPSCunbounded[TaskNode]` is made intrusive, the cacheline alignment requirements automatically mades it take over 64 bytes.
Also even if the back/count/front are tagged with 64 bytes alignment each (total 192 bytes)
https://github.com/mratsim/weave/blob/71cf68137bd27e9ba175b468a342a8e61a647faa/weave/channels/channels_mpsc_unbounded_batch.nim#L50-L80
the extra deferredIn, deferredOut, fulfilled fields are not using the extra …
> Update mpsc padding

- .travis.yml
- README.md
- azure-pipelines.yml
- weave.nimble
- weave/victims.nim
The latest Nim stable v1.2.0 integrates critical requirement for Weave:
- The `{.align.}` pragma https://github.com/nim-lang/Nim/pull/12643, https://github.com/nim-lang/Nim/pull/12666
- Enums as Atomic types https://github.com/nim-lang/Nim/issues/12812
This means that Weave can now target a stable release.
A workaround to reenable C++ compilation (by disabling Pledges) will be added in a separate PR (bug: https://github.com/nim-lang/Nim/issues/13062)
> Update from devel to Nim v1.2.0

- weave/memory/memory_pools.nim
This magic 1-liner commit reduces the overhead of eager futures by over 40% and closes #112 
We are back to being way under Intel TBB (600 ms) and Intel TBB has the lowest overhead compared to all frameworks used in production for task parallelism: OpenMP (GCC, LLVM/Intel) or Julia Partr or HPX
> 40+% overhead reduction of memory pool on overhead-bound benchmarks

- weave/contexts.nim
- weave/cross_thread_com/channels_mpsc_unbounded_batch.nim
- weave/cross_thread_com/pledges.nim
- weave/datatypes/context_global.nim
- weave/memory/memory_pools.nim
- weave/runtime.nim
This does 2 things:
- MPSC count is now optional, implementing the last part of #93
- MPSC count sanity checks does not load(moRelaxed) but directly check the old count returned by fetchAdd
This should:
- fix https://github.com/mratsim/weave/issues/49 
- fix https://github.com/mratsim/weave/issues/85
- close #93
> Change mpsc counting

- weave/datatypes/prell_deques.nim
- weave/executor.nim
- weave/parallel_jobs.nim
- weave/runtime.nim
- weave/victims.nim
This PR does:
- ensure that Weave compiles without Backoff after #136 
- A parent will give half its tasks when waking up its children, whatever they requested.
This solves #90 by diffusing tasks much faster to the leaves.
Impact is 10% overhead reduction on fibonacci: 
- This should significantly help when Weave is used as a background service as well.
> Load balance child wakeup

- benchmarks/matmul_gemm_blas/test_gemm_output.nim
- demos/raytracing/README.md
- demos/raytracing/smallpt.nim
- weave.nimble
This removes testing the raytracing demo on Windows as it doesn't implement erand48 (from <stdlib.h>)
It also reduces the number of matrix sizes fuzzed in Matrix Multiplication see #149.
This reduces the noise in CI to ensure we don't miss regressions.
> Reduce CI noise

- tests/README.md
- weave/datatypes/prell_deques.nim
- weave/executor.nim
- weave/scheduler.nim
- weave/state_machines/sync_root.nim
- weave/victims.nim
This fixes https://github.com/mratsim/weave/issues/155, the format that addListFirst(head, tail) cannot use the raw output of tryRecvBatch for some reason.
https://github.com/mratsim/weave/blob/8568cd351d97406a3ef01557e0a6faab0e18bb4a/weave/victims.nim#L311-L324
This also adds more assertions.
> Executor fixes

- weave.nimble
The Nim repo executes `nimble test_gc_arc` to make sure weave works on devel. But weave needs cligen dep to run `weave/benchmarks/matrix_transposition/weave_transposes.nim`. It got error:
```
/home/runner/work/Nim/Nim/pkgstemp/weave/benchmarks/matrix_transposition/
weave_transposes.nim(16, 3) Error: cannot open file: cligen
```
ref https://github.com/nim-lang/Nim/pull/19762
> install deps for tests
